### PR TITLE
Make description of `keep` more accurate.

### PR DESCRIPTION
**Pull request by tmccombs**

### CODE REVIEW

**Comment by tmccombs** [comment]
Ok, closing in favor of #6

**Comment by tmccombs** [comment]
@ruricolist What do you use to generate reference.md?

**Comment by ruricolist** [comment]
It's a few functions written for the purpose; I think I based them off an earlier version of Quickdocs. Basically, use Swank to figure out what's defined where and ASDF to get the order of the files.

In theory it should be incorporated into the repo somehow, but there's no obviously correct approach with ASDF.

**Comment by ruricolist** [comment]
For reference, the code is now included in the repository:

https://github.com/TBRSS/serapeum/blob/master/docs.lisp

**Pull request closed without merging**
