### PR TITLE
Add .travis.yml and build status badge

### PR DESCRIPTION
**Pull request by eudoxia0**
This PR adds a `.travis.yml` file to test the library on the cloud using SBCL, CCL and Allegro, and adds a build status badge to the README.

### CODE REVIEW

**Comment by ruricolist** [comment]
Merged, thanks.

**Comment by eudoxia0** [comment]
Minor thing I forgot: You have to sign in on [Travis](travis-ci.org) with your GitHub account, and probably enable the repo manually.

**Comment by ruricolist** [comment]
That's done. I take it I have to actually push something to get it to build?

**Comment by eudoxia0** [comment]
Yes. It's a shame they don't have a button to explicitly start builds, but w/e.

**Pull request merged**
